export type WindowsChannel =
  | 'sub'
  | 'size'
  | 'etcSize'
  | 'show-menu'
  | 'hide-menu'
  | 'hideMenuWindow'
  | 'closeMenuWindow'
  | 'sizeUpMenuWindow'
  | 'start-move'
  | 'stop-move'
  | 'weatherHandler'
  | 'start-drag'
  | 'stop-drag'
  | 'windowOpened'
  | 'windowClosed'
  | 'showYouTubeMusicWindow'
  | 'hideYouTubeMusicWindow';
